//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoMIDroid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_tab_artists_grey = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_tab_artists_white = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_tab_zone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int light_bulb_off = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int light_bulb_on = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logo_small = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int minus = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int plus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int switch_OFF = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int switch_ON = 2130837514;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int LinearLayout1 = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int action = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int deviceDIM_btn_minus = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int deviceDIM_btn_plus = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int deviceDIM_seekBar = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int deviceDIM_txtName = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int deviceDIM_txtPercent = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int deviceDim_btnAction = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int deviceOnOff_btnAction = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int deviceOnOff_txtName = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int imageView1 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int login_btn_login = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int login_et_id = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int login_et_port = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int login_et_server = 2131034126;
			
			// aapt resource value: 0x7f050015
			public const int login_tv_id = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int login_tv_port = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int login_tv_server = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int name = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int textView2 = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int valueText = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int widget28 = 2131034119;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DeviceDim = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DeviceList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DeviceOnOff = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListItemBasicDevice = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListItemOnOffDevice = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TabZone = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TestItem = 2130903048;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
