@ECHO OFF
ECHO *** CIS
hitb.exe -cis
IF %ERRORLEVEL% == 0 ECHO SVC NOT INSTALLED
IF %ERRORLEVEL% == 1 ECHO SVC INSTALLED

ECHO *** CRS
hitb.exe -crs
IF %ERRORLEVEL% == 0 ECHO SVC NOT RUNNING
IF %ERRORLEVEL% == 1 ECHO SVC RUNNING

ECHO *** CRA
hitb.exe -cra
IF %ERRORLEVEL% == 0 ECHO APP NOT RUNNING
IF %ERRORLEVEL% == 1 ECHO APP RUNNING

ECHO ***DPI
hitb.exe -dpi
IF %ERRORLEVEL% == 0 ECHO PREVIOUS INSTALL NOT DETECTED
IF %ERRORLEVEL% == 1 ECHO PREVIOUS INSTALL DETECTED

PAUSE