//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoMIDroid
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int composant = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_tab_artists_grey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_tab_artists_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_zone = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int light_bulb_off = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int light_bulb_on = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo_small = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logout = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int minus = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int plus = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int refresh = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int switch_OFF = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int switch_ON = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int zone = 2130837518;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int LinearLayout1 = 2131099656;
			
			// aapt resource value: 0x7f06000f
			public const int action = 2131099663;
			
			// aapt resource value: 0x7f060004
			public const int deviceDIM_btn_minus = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int deviceDIM_btn_plus = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int deviceDIM_seekBar = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int deviceDIM_txtName = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int deviceDIM_txtPercent = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int deviceDim_btnAction = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int deviceOnOff_btnAction = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int deviceOnOff_txtName = 2131099657;
			
			// aapt resource value: 0x7f060013
			public const int imageView1 = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int imgItemDevice = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout1 = 2131099659;
			
			// aapt resource value: 0x7f060014
			public const int login_btn_login = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int login_et_id = 2131099670;
			
			// aapt resource value: 0x7f060012
			public const int login_et_port = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int login_et_server = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int login_tv_id = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int login_tv_port = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int login_tv_server = 2131099665;
			
			// aapt resource value: 0x7f06000c
			public const int name = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int textView2 = 2131099649;
			
			// aapt resource value: 0x7f06000d
			public const int valueText = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int widget28 = 2131099655;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int deviceDim = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int deviceList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int deviceOnOff = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int index = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int listItemBasicDevice = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int listItemOnOffDevice = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int tabZone = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int testItem = 2130903049;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Quit = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Refresh = 2130968577;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int boldText = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int disabledText = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int normalText = 2131034113;
			
			private Style()
			{
			}
		}
	}
}
