'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WpfApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Defaut_Img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Defaut_Img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &apos;EXEMPLE *******************************************
        '''&apos;***************************************************
        '''Imports System
        '''Imports System.IO
        '''Imports System.Windows.Forms
        '''Imports Microsoft.VisualBasic
        '''Imports Homidom                                                                  
        '''Namespace Dynam
        ''' &apos;Ne pas supprimer cette class
        ''' Public Class DynamicCode
        '''   
        '''  &apos;Ne pas supprimer cette function 
        '''  Public Function ExecuteCode(paramarray prmParameters() as object) as object
        '''    Dim Serveur as Homidom.H [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property ExempleVBS() As String
            Get
                Return ResourceManager.GetString("ExempleVBS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à XXXX0001;------- BELGIQUE --------
        '''
        '''BEXX0034;Aalst
        '''BEXX0035;Aalter
        '''BEXX0036;Aarschot
        '''BEXX0038;Aiseau
        '''BEXX0039;Alken
        '''BEXX0041;Amay
        '''BEXX0042;Ambleve
        '''BEXX0043;Andenne
        '''BEXX0001;Anderlecht
        '''BEXX0045;Anhee
        '''BEXX0002;Ans
        '''BEXX0046;Antoing
        '''BEXX0003;Anvers
        '''BEXX0047;Anzegem
        '''BEXX0048;Ardooie
        '''BEXX0050;Arlon
        '''BEXX0051;As
        '''BEXX0052;Asse
        '''BEXX0055;Ath
        '''BEXX0057;Avelgem
        '''BEXX0058;Awans
        '''BEXX0004;Aywaille
        '''BEXX0059;Balen
        '''BEXX0060;Basse Lasne
        '''BEXX0061;Bassenge
        '''BEXX0062;Bastogne
        '''BEXX0065;Beernem
        '''BEXX0066;Be [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property WeatherCityID_BE() As String
            Get
                Return ResourceManager.GetString("WeatherCityID_BE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à XXXX0000;-------- FRANCE ---------
        '''FRXX1438;Abancourt
        '''FRXX0111;Abbeville
        '''FRXX1570;Ablon-sur-Seine
        '''FRXX5930;Abondant
        '''FRXX4851;Abscon
        '''FRXX1220;Achen
        '''FRXX5834;Achenheim
        '''FRXX5109;Acheres
        '''FRXX3754;Acheres-la-Foret
        '''FRXX1618;Acigne
        '''FRXX1542;Aeroport D&apos;Orly
        '''FRXX4397;Agde
        '''FRXX0135;Agen
        '''FRXX2840;Agon-Coutainville
        '''FRXX3723;Aibes
        '''FRXX6269;Aigues-Vives
        '''FRXX2409;Aiguilles
        '''FRXX7004;Ailly-sur-Somme
        '''FRXX1137;Aimargues
        '''FRXX0328;Aire-sur-l&apos;Adour
        '''FRXX0001;Aix-en-Provence
        '''FRXX0129;Ajaccio
        '''FRXX0002;Albi
        '''F [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend ReadOnly Property WeatherCityID_FR() As String
            Get
                Return ResourceManager.GetString("WeatherCityID_FR", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
